// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Counterparties.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240313100416_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CreditContract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("CreditCounterparty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreditContractId")
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("nvarchar(34)");

                    b.HasKey("Id");

                    b.HasIndex("CreditContractId");

                    b.ToTable("CreditCounterparty");

                    b.HasDiscriminator<string>("Discriminator").HasValue("CreditCounterparty");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("CorporateCreditCounterparty", b =>
                {
                    b.HasBaseType("CreditCounterparty");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("CorporateCreditCounterparty");
                });

            modelBuilder.Entity("PrivateCreditCounterparty", b =>
                {
                    b.HasBaseType("CreditCounterparty");

                    b.Property<string>("PersonName")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("PrivateCreditCounterparty");
                });

            modelBuilder.Entity("CreditCounterparty", b =>
                {
                    b.HasOne("CreditContract", null)
                        .WithMany("Counterparties")
                        .HasForeignKey("CreditContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CreditContract", b =>
                {
                    b.Navigation("Counterparties");
                });
#pragma warning restore 612, 618
        }
    }
}
